jars:
  - path: "C:\\workspace\\Api\\tx-auth-api\\target\\tx-auth-api-0.0.1-SNAPSHOT.jar"
    profile: "test"
  - path: "C:\\workspace\\User\\tx-user-api\\target\\tx-user-api-0.0.1-SNAPSHOT.jar"
    profile: "test"
  - path: "C:\\workspace\\Api\\tx-api-forwarder\\target\\tx-api-forwarder-0.0.1-SNAPSHOT.jar"
    profile: "test"

#jars:
#  - path: "C:\\workspace\\tx-auth-api\\target\\tx-auth-api-0.0.1-SNAPSHOT.jar"
#    profile: "test"
#  - path: "C:\\workspace\\User\\tx-user-api\\target\\tx-user-api-0.0.1-SNAPSHOT.jar"
#    profile: "test"